//GAME CONFIG
//Default configuration for game modes

export const DEFAULT_CONFIG = {
    PLAYER_LIVES: 5,
    INVADERS_ROWS: 5,
    INVADERS_COLS: 10,
    CRAB_SPEED_BASE: 1,
    GAME_SPEED_LEVEL_INCREASE: 0.07,
    CRAB_SPEED_LEVEL_INCREASE: 0.25
};

export const TOURNAMENT_CONFIG = {
    PLAYER_LIVES: 5,
    INVADERS_ROWS: 5,
    INVADERS_COLS: 10,
    CRAB_SPEED_BASE: 1,
    GAME_SPEED_LEVEL_INCREASE: 0.07,
    CRAB_SPEED_LEVEL_INCREASE: 0.25
};

export const CORALUNA_CONFIG = {
    PLAYER_LIVES: 5,
    INVADERS_ROWS: 5,
    INVADERS_COLS: 10,
    CRAB_SPEED_BASE: 1,
    GAME_SPEED_LEVEL_INCREASE: 0.07,
    CRAB_SPEED_LEVEL_INCREASE: 0.25
};
